apiVersion: v1
kind: Pod
metadata:
  name: mesos-cluster-master
  namespace: default
spec:
  hostNetwork: true
  containers:
    - name: zookeeper
      image: jplock/zookeeper:3.4.8
      volumeMounts:
        - mountPath: /opt/zookeeper/conf/zoo.cfg
          name: zoocfg
          readOnly: true
        - mountPath: /var/lib/zookeeper/data/myid
          name: zoomyid
          readOnly: true
        - mountPath: /tmp/zookeeper
          name: zoodata
    - name: mesos-master
      image: mesosphere/mesos:0.28.0-2.0.16.ubuntu1404
      command:
        - /bin/bash
        - -c
        - . /etc/default/mesos-master; /usr/sbin/mesos-master
      volumeMounts:
        - mountPath: /etc/default/mesos
          name: mesosmasterdefaultconfig
          readOnly: true
        - mountPath: /etc/default/mesos-master
          name: mesosmasterdefaultconfig
          readOnly: true
        - mountPath: /etc/mesos
          name: mesosconfig
          readOnly: true
        - mountPath: /etc/mesos-master
          name: mesosmasterconfig
          readOnly: true
  volumes:
    - name: zoocfg
      hostPath:
        path: /etc/zookeeper/conf/zoo.cfg
    - name: zoomyid
      hostPath:
        path: /var/lib/zookeeper/data/myid
    - name: mesoswork
      emptyDir: {}
    - name: mesoslogs
      emptyDir: {}
    - name: zoodata
      emptyDir: {}
    - name: mesosmasterdefaultconfig
      hostPath:
        path: /etc/default/mesos-master
    - name: mesosconfig
      emptyDir: {}
    - name: mesosmasterconfig
      emptyDir: {}