#!/bin/bash

HOSTNAME=$(/bin/hostname)

export KUBE_APISERVER_OPTS="
  --insecure-bind-address=0.0.0.0 \
  --insecure-port=8080 \
  --secure-port=0 \
  --etcd-servers=http://172.28.128.101:2379,http://172.28.128.102:2379,http://172.28.128.103:2379 \
  --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota \
  --service-cluster-ip-range=10.10.10.0/24 \
  --v=4 \
  --log-dir='/var/log/kube/${HOSTNAME}' \
  --logtostderr=false \
  --alsologtostderr=true \
  --allow-privileged=false "