#!/bin/bash

HOSTNAME=$(/bin/hostname)
IP=$(ifconfig eth1 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1)

export KUBE_APISERVER_OPTS=" \
  --apiserver-count=3 \
  --insecure-bind-address=0.0.0.0 \
  --insecure-port=8080 \
  --secure-port=0 \
  --etcd-servers=http://k8s-master01:2379,http://k8s-master02:2379,http://k8s-master03:2379 \
  --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota \
  --service-cluster-ip-range=10.10.10.0/24 \
  --v=4 \
  --log-dir='/var/log/kube/${HOSTNAME}' \
  --logtostderr=false \
  --alsologtostderr=true \
  --allow-privileged=false \
  --cloud-provider=mesos \
  --cloud-config=/etc/mesos-cloud.conf
  "