#!/bin/bash

HOSTNAME=$(hostname)

export KUBELET_OPTS=" \
  --address=0.0.0.0 \
  --allow-privileged=true \
  --logtostderr=false \
  --alsologtostderr=true \
  --config="/etc/kubernetes/manifests/" \
  --container-runtime="docker" \
  --enable-server=true \
  --file-check-frequency=30s \
  --http-check-frequency=30s \
  --node-status-update-frequency=1m \
  --log-dir="/vagrant/kubelet/logs/${HOSTNAME}" \
  --log-flush-frequency=5s \
  --read-only-port=10255 \
  --register-node=false \
  --sync-frequency=10s \
  --cluster-dns=10.10.10.10 \
  --cluster-domain=cluster.local \
  --v=2 "