#!/bin/bash

export KUBELET_OPTS=" \
  --address=0.0.0.0 \
  --allow-privileged=false \
  --logtostderr=false \
  --alsologtostderr=true \
  --api-servers=172.28.128.101:8080,172.28.128.102:8080,172.28.128.103:8080 \
  --config="/vagrant/kubelet/manifests-slave" \
  --container-runtime="docker" \
  --enable-server=true \
  --file-check-frequency=30s \
  --http-check-frequency=30s \
  --node-status-update-frequency=1m \
  --log-dir="/vagrant/kubelet/logs/${HOSTNAME}" \
  --log-flush-frequency=5s \
  --read-only-port=10255 \
  --register-node=true \
  --sync-frequency=10s \
  --cluster-dns=10.10.10.10 \
  --cluster-domain=cluster.local \
  --v=2 "