apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: gcr.io/google_containers/kube-scheduler:v1.2.0
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-scheduler 
      --master=127.0.0.1:8080
      --v=4
      --log-dir="/var/log/kube/${HOSTNAME}"
      --logtostderr=false
      --alsologtostderr=true
      --leader-elect=true
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /var/log/kube/
      name: logfile
  volumes:
  - hostPath:
      path: /vagrant/scheduler/logs
    name: logfile