apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - mountPath: /etc/nginx/nginx.conf
        name: nginxconf
        readOnly: true
  volumes:
    - name: nginxconf
      hostPath:
        path: /etc/default/nginx

