apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    k8s-app: nginx
    tier: web-ui
    kubernetes.io/cluster-service: "true"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
