#!/bin/bash

HOSTNAME=$(/bin/hostname)
IP=$(ifconfig eth1 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1)

export FLANNEL_OPTS=" \
  -etcd-endpoints=\"http://172.28.128.101:2379,http://172.28.128.102:2379,http://172.28.128.103:2379\" \
  -ip-masq \
  -alsologtostderr=true \
  -log_dir="/vagrant/flanneld/logs/${HOSTNAME}" \
  -logtostderr=false \
  -public-ip="${IP}" \
  -v=4 \
  -iface=eth1 "