#!/bin/bash

HOSTNAME=$(/bin/hostname)

export KUBE_CONTROLLER_MANAGER_OPTS="
  --master=127.0.0.1:8080 \
  --alsologtostderr=true \
  --log-dir='/var/log/kube/${HOSTNAME}' \
  --logtostderr=false \
  --v=4 \
  --leader-elect=true "